### ISSUE TITLE
[Android] Purchase not acknowledged/consumed, if app is closed when deferred purchase completes

### ISSUE THREAD

**Issue by WiseKodama** [qonversion/unity-sdk#228]
Steps to reproduce:
* Start purchase and select slow test card, approves after a few minutes
* Kill app
* Wait for purchase to complete(1 minute)
* Open app

Result:
* Using CheckEntitlements after Initialize it will return that the purchase has completed successfully and the entitlement is given to the user, **HOWEVER** Google will cancel the purchase because it was not acknowledged by Qonversion. 

Currently I was unable to find a way to manually acknowledge/consume a purchase via API.
Since out of app purchases can happen on Android(preregistration, deferred) this should work out of the box...

**Comment by OxanaGorya** [comment]
@WiseKodama Hello!
We fixed the bug in the latest version. Please update and let me know if you still have the issue, or if you've already updated and the problem persists. Thank you!

**Comment by WiseKodama** [comment]
Thank you @OxanaGorya , will test this today and report back.

**Comment by WiseKodama** [comment]
Apologies for the late response. I have tested the flow and it is now working as expected. The purchase is no longer cancelled thus meaning it was consumed. 

Thank you.
