### ISSUE TITLE
Can't build for iOS

### ISSUE THREAD

**Issue by aratn0n** [qonversion/unity-sdk#33]
Hello, I got these errors when I built my project on Xcode. I imported the SDK via Git and I'm using Xcode 13.0.
`
com.qonversion.unity/Runtime/iOS/Plugins/Common/UtilityBridge.m:68:31: Definition of 'QNPermission' must be imported from module 'Qonversion.QNPermission' before it is required`

`com.qonversion.unity/Runtime/iOS/Plugins/Common/UtilityBridge.m:89:43: Definition of 'QNProduct' must be imported from module 'Qonversion.QNProduct' before it is required`

`com.qonversion.unity/Runtime/iOS/Plugins/Common/UtilityBridge.m:68:31: Definition of 'QNPermission' must be imported from module 'Qonversion.QNPermission' before it is required`

`com.qonversion.unity/Runtime/iOS/Plugins/Common/UtilityBridge.m:89:43: Definition of 'QNProduct' must be imported from module 'Qonversion.QNProduct' before it is required`

**Comment by suriksarkisyan** [comment]
Hi, @aratn0n 
I'll suppose the Qonversion iOS SDK can not be found.
Could you please check does the Qonversion iOS SDK is installed?

**Comment by aratn0n** [comment]
I installed it by adding the SDK reposition to the `Packages/manifest.json`. I'm using Unity 2019.4.31f1.
Do I have to resolve the dependency on iOS? Does cocopods do all the work when building the project on Xcode?

**Comment by Nordup** [comment]
Hi :) I have the same issue in Unity Cloud Build with Xcode 13.0 It builds on my Mac Pro M1 with Xcode 13.2 How can I solve this?

**Comment by suriksarkisyan** [comment]
Hi @Nordup 
Give me a little bit of time, please. I'll come back with a solution today 🙏

**Comment by Nordup** [comment]
@suriksarkisyan Thank you very much! I really appreciate your help

**Comment by suriksarkisyan** [comment]
Hi guys ✌️
Sorry for the late reply! 😔
We just updated the [install documentation](https://documentation.qonversion.io/docs/unity-sdk). 
Could you please install our Unity SDK and native dependencies step by step as described in the documentation and let me know if the problem is still occurring 😊

**Comment by pixelfoxxx** [comment]
Hi @aratn0n and @Nordup. Did you manage to deal with the issue? If yes, great! Just let us know, and we’ll close out this conversation.

**Comment by OliverRiisager** [comment]
I am also having this issue on Unity Cloud build. I have followed your installation guide, both as a scoped registry and as a git url.

**Comment by OliverRiisager** [comment]
@Nordup did you fix this? If so, how did you do it?

**Comment by OliverRiisager** [comment]
How do you mean resolved? In an updated version or?

**Comment by OliverRiisager** [comment]
@pixelfoxxx is that fix in 3.2.1 or do i need to update to 3.4.1? Or is there some setting i need to look at?

**Comment by OliverRiisager** [comment]
I fixed this issue by upgrading plugin version to 3.4.1. But got another issue instead - i opened an issue on this as well here : https://github.com/qonversion/unity-sdk/issues/77

**Comment by Nordup** [comment]
Hi! I think issue resolved. We've upgraded to 3.4.1 and everything seems good. Sorry for the late replay

**Comment by OliverRiisager** [comment]
No worries 😊 we did the same thing and that resolved the issue. We just
started out by following the install guide, but that version doesn't work -
so we thought it might have been related to some settings.
