### ISSUE TITLE
Broken singleton

### ISSUE THREAD

**Issue by OliverRiisager** [qonversion/unity-sdk#76]
The Qonversion monobehaviour's getFinalInstance will create multiple gameobjects over the course of its lifetime.
As seen below - it doesnt respect the null check of the instance. 
![image](https://user-images.githubusercontent.com/62520142/166125153-dfaed118-1fc5-4c4a-867a-9a0d8764b05c.png)
![image](https://user-images.githubusercontent.com/62520142/166125390-081e5d6a-935a-48cf-8fad-b2271d824c66.png)

The above might be a solution to this issue. However, I can't tell if theres a good reason this is a monobehaviour? The object is never destroyed, and every public method is static anyways, and it doesnt seem as if any gameobject related functionality is used.

**Comment by suriksarkisyan** [comment]
Hi, @OliverRiisager 
Thank you for contacting us. I'll explore the problem and come back ASAP!
