### ISSUE TITLE
PurchaseProduct isCancelled is missing in the callback

### ISSUE THREAD

**Issue by AytoMaximo** [qonversion/unity-sdk#84]
Hello! I have problem with getting purchase was cancelled callback. Seems like it was missed in the Unity SDK and Unity documentation, however Unity is cross-platform engine with iOS support too. 

Can you please add this feature or tell me where I can find it if exists.

**Comment by SpertsyanKM** [comment]
Hello! Thank you for your feedback. There is no `isCancelled` flag in Unity on purchase response for now. I will discuss supporting it in Unity SDK with our team and will return to you with the answer soon.

**Comment by SpertsyanKM** [comment]
Happy to say that we are going to add this flag in our future SDK release, so stay connected! It will be available soon.

**Comment by AytoMaximo** [comment]
We're glad to here this, thank you! Can't wait :)

**Comment by SpertsyanKM** [comment]
We have released the [new version](https://github.com/qonversion/unity-sdk/releases/tag/3.4.4) 3.4.4 of the Unity SDK which returns the `isCancelled` flag to the purchase delegate. Please, try it out, and feel free to contact us if you have any further questions!
